name: Run Proxy Rental Script

# This workflow will run manually
on:
  workflow_dispatch:

jobs:
  run_proxy_rental:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment and install necessary dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change to your Python version if needed

      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium

      # Step 3: Run the Python script
      - name: Run proxy-rental script

        env:
          D_USERNAME_SECRET: ${{ secrets.D_USERNAME_SECRET }}
          D_PASSWORD_SECRET: ${{ secrets.D_PASSWORD_SECRET }}
        run: |
          python proxy-rental.py

      # Step 4: Commit and push the JSON file
      - name: Commit and push generated JSON
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # GitHub Personal Access Token
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add proxy-rental-link.json
          git commit -m "Add or update proxy-rental-link.json"
          git push origin HEAD:main  # Change 'main' to your default branch if needed
